version: '3.3'
services:
  database:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  database-data: null
